// flow-typed signature: 1636b0f3655844904d0e9ea8e77abf1e
// flow-typed version: <<STUB>>/synchronous-promise_v^1.0.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'synchronous-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'synchronous-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'synchronous-promise/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'synchronous-promise/index' {
  declare module.exports: $Exports<'synchronous-promise'>;
}
declare module 'synchronous-promise/index.js' {
  declare module.exports: $Exports<'synchronous-promise'>;
}
declare module 'synchronous-promise/index.spec.js' {
  declare module.exports: $Exports<'synchronous-promise/index.spec'>;
}
